### PR TITLE
Fcgi spawn

### LINKED ISSUE #9: Spawn multiple php-cgi instances
Currently, there is only one cgi process, which is quite insufficient. Would be nice, if would be possible to allow more intances. At this time I have to use https://bitbucket.org/cybergene/spawn-php/wiki/Home

### PR DESCRIPTION
**Pull request by hrach**
closes #9

### CODE REVIEW

**Comment by hrach** [comment]
Searching running processes is done only on startup. What do you think? It's a little bit less powerful, but it shoud fit the most common needs.

**Comment by hrach** [comment]
so, merge/close/review :-)

**Comment by hrach** [comment]
ping :-) using the whole time, works ok :-)

**Comment by hrach** [comment]
What now? :)

**Comment by JanTvrdik** [comment]
now I still have no time for this, sorry

**Comment by hrach** [comment]
Added fix for nginx, which creates subprocesses and it's quite hard to kill it properly :)

**Pull request merged**
